version: '2'
services:
    db:
        container_name: db
        image: postgres:9.5
        ports:
          - "127.0.0.1:5434:5432"
        environment:
          - POSTGRES_USER=odoo
          - POSTGRES_PASSWORD=odoo
        volumes:
          - db-data:/var/lib/postgresql/data
volumes:
    db-data:
